
prefix bf: <http://id.loc.gov/ontologies/bibframe/>
prefix cs: <http://www.kulttuurisampo.fi/ebkr/>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix hg: <http://rdf.histograph.io/>
prefix sd: <http://www.w3.org/ns/sparql-service-description#>
prefix vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
prefix bgn: <http://biographynet.nl/schema/>
prefix dbo: <http://dbpedia.org/ontology/>
prefix edm: <http://www.europeana.eu/schemas/edm/>
prefix gvp: <http://vocab.getty.edu/ontology#>
prefix ore: <http://www.openarchives.org/ore/terms/>
prefix org: <http://www.w3.org/ns/org#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix pnv: <http://archief.nl/pnv/def/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix iiif: <http://iiif.io/api/image/2#>
prefix odrl: <http://www.w3.org/ns/odrl/2/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix svcs: <http://rdfs.org/sioc/services#>
prefix void: <http://rdfs.org/ns/void#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix frbroo: <http://iflastandards.info/ns/fr/frbr/frbroo/>
prefix premis: <http://www.loc.gov/premis/rdf/v3/>
prefix schema: <http://schema.org/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix eac-cpf: <http://www3.iath.virginia.edu/eac/cpf/>
prefix ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#>
prefix dctypens: <http://purl.org/dc/dcmitype/>
prefix cidoc-crm: <http://www.cidoc-crm.org/cidoc-crm/>
prefix frbr_core: <http://purl.org/vocab/frbr/core#>
prefix fibo-fnd-oac-own: <https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Ownership/>
prefix fibo-fnd-pty-pty: <https://spec.edmcouncil.org/fibo/ontology/FND/Parties/Parties/>


## query

prefix naa: <http://archief.nl/def/>
prefix bf: <http://id.loc.gov/ontologies/bibframe/>
prefix cs: <http://www.kulttuurisampo.fi/ebkr/>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix hg: <http://rdf.histograph.io/>
prefix sd: <http://www.w3.org/ns/sparql-service-description#>
prefix vs: <http://www.w3.org/2003/06/sw-vocab-status/ns#>
prefix bgn: <http://biographynet.nl/schema/>
prefix dbo: <http://dbpedia.org/ontology/>
prefix edm: <http://www.europeana.eu/schemas/edm/>
prefix gvp: <http://vocab.getty.edu/ontology#>
prefix ore: <http://www.openarchives.org/ore/terms/>
prefix org: <http://www.w3.org/ns/org#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix pnv: <http://archief.nl/pnv/def/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix iiif: <http://iiif.io/api/image/2#>
prefix odrl: <http://www.w3.org/ns/odrl/2/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix svcs: <http://rdfs.org/sioc/services#>
prefix void: <http://rdfs.org/ns/void#>
prefix vcard: <http://www.w3.org/2006/vcard/ns#>
prefix frbroo: <http://iflastandards.info/ns/fr/frbr/frbroo/>
prefix premis: <http://www.loc.gov/premis/rdf/v3/>
prefix schema: <http://schema.org/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix eac-cpf: <http://www3.iath.virginia.edu/eac/cpf/>
prefix ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#>
prefix dctypens: <http://purl.org/dc/dcmitype/>
prefix cidoc-crm: <http://www.cidoc-crm.org/cidoc-crm/>
prefix frbr_core: <http://purl.org/vocab/frbr/core#>
prefix fibo-fnd-oac-own: <https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Ownership/>
prefix fibo-fnd-pty-pty: <https://spec.edmcouncil.org/fibo/ontology/FND/Parties/Parties/>

select * {
  ?s naa:isAggregationType naa:TypePhotoRecord ;
       edm:isShownBy ?o .
     ?o dcterms:source ?url ;
   } limit 10
